image: jugit-registry.fz-juelich.de/ibg-1/modsim/moovie/moovie:test

stages:
  - build
  - test
  - publish

build-cli:
  stage: build
  script:
    - mkdir build-cli
    - cd build-cli
    - cmake .. -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_BUILD_TYPE=Debug -DBUILD_LIB=ON -DBUILD_GUI=OFF -DBUILD_TESTS=ON -DBUILD_DOCUMENTATION=OFF
    - cmake --build . -j4
  artifacts:
    when: always
    expire_in: 14 days
    paths:
      - build-cli


build-qt5:
  stage: build
  script:
    - mkdir build-qt5
    - cd build-qt5
    - cmake .. -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_BUILD_TYPE=Release -DBUILD_LIB=ON -DBUILD_GUI=ON -DQT_VERSION=QT5 -DBUILD_TESTS=OFF -DBUILD_DOCUMENTATION=OFF
    - cmake --build . -j4
  artifacts:
    when: always
    expire_in: 14 days


build-qt6:
  stage: build
  script:
    - mkdir build-qt6
    - cd build-qt6
    - cmake .. -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_BUILD_TYPE=Release -DBUILD_LIB=ON -DBUILD_GUI=ON -DQT_VERSION=QT6 -DBUILD_TESTS=OFF -DBUILD_DOCUMENTATION=OFF
    - cmake --build . -j4
  artifacts:
    when: always
    expire_in: 14 days


unit_test:
  stage: test
  script:
    - cd build-cli
    - ctest --extra-verbose
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR} --filter ${CI_PROJECT_DIR}/src/main/cpp/lib
    - cd ..
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    when: always
    expire_in: 14 days
    reports:
      junit:
        - build-cli/src/test/report_configuration_test.xml
        - build-cli/src/test/report_dataset_test.xml
        - build-cli/src/test/report_storageelements_test.xml
        - build-cli/src/test/report_coordinates_test.xml
        - build-cli/src/test/report_graphicalelements_test.xml
        - build-cli/src/test/report_utilities_test.xml
      coverage_report:
        coverage_format: cobertura
        path: build-cli/coverage.xml


build-documentation:
  image: sphinxdoc/sphinx:latest
  stage: build
  before_script:
    - apt-get update -y
    - apt-get install -y doxygen cmake
  script:
    - mkdir build-docs
    - cd build-docs
    - cmake .. -DCMAKE_PREFIX_PATH=/usr/local -DBUILD_LIB=OFF -DBUILD_DOCUMENTATION=ON
    - make html
  artifacts:
    paths:
    - docs/build/html/*
    expire_in: 1 week
  only:
    - build_documentation

publish-documentation:
  image: ubuntu:22.04
  stage: publish
  script:
    - echo "TODO"
  dependencies:
    - build-documentation
  only:
    - build_documentation


build-container:
  image: ubuntu:22.04
  stage: publish
  before_script:
    - apt-get update
    - apt-get install -y docker.io
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/ibg-1/modsim/moovie/moovie:test .
    - docker push $CI_REGISTRY/ibg-1/modsim/moovie/moovie:test
  only:
    - develop
