image: jugit-registry.fz-juelich.de/ibg-1/modsim/moovie

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_DOCUMENTATION=OFF
    - cmake --build .
  artifacts:
    when: always
    expire_in: 14 days
    paths:
      - build

unit_test:
  before_script:
    - apt-get -y install gcovr
  script:
    - cd build
    - ctest --extra-verbose
    - cd -
    - gcovr -e build -r .
  artifacts:
    when: always
    expire_in: 14 days
    reports:
      junit:
        - build/src/test/report_configuration_test.xml  
        - build/src/test/report_dataset_test.xml
        - build/src/test/report_storageelements_test.xml
        - build/src/test/report_coordinates_test.xml    
        - build/src/test/report_graphicalelements_test.xml  
        - build/src/test/report_utilities_test.xml

