version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install sphinx exhale myst-parser sphinx-book-theme
    - sed s,\${PROJECT_SOURCE_DIR},$(pwd),g Doxyfile.in > Doxyfile
    - doxygen Doxyfile
    - cd docs && make html
    - mkdir -p ${READTHEDOCS_OUTPUT}
    - cp -r docs/build/html ${READTHEDOCS_OUTPUT}
